#!/usr/bin/env python3
"""Generate the GitHub Copilot CLI layer from the canonical Claude Code sources.

The repository keeps a single source of truth:

    agents/*.md                  - QA phase sub-agents (Claude Code)
    commands/*.md                - slash commands (Claude Code)
    skills/quality-engineer/     - the judgement-layer skill (Claude Code)

GitHub Copilot CLI uses the same building blocks under different conventions:

    .github/agents/<name>.agent.md          - custom agents
    .github/skills/quality-engineer/SKILL.md - agent skill

This script emits that .github/ tree so both ecosystems stay in sync from one
source. Run it after editing anything under agents/, commands/ or skills/.

Usage:
    python3 scripts/build-copilot.py          # write the .github/ tree
    python3 scripts/build-copilot.py --check   # fail if the tree is stale (CI)

Zero third-party dependencies - standard library only.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Canonical source directories.
AGENTS_SRC = ROOT / "agents"
COMMANDS_SRC = ROOT / "commands"
SKILL_SRC = ROOT / "skills" / "quality-engineer"

# Generated Copilot CLI targets.
AGENTS_OUT = ROOT / ".github" / "agents"
SKILL_OUT = ROOT / ".github" / "skills" / "quality-engineer"

# Body rewrites applied to agent/command markdown (NOT to skill files, whose
# internal references are already skill-relative).
PATH_REWRITES = [
    # The skill moves from skills/ to .github/skills/ in the Copilot layer.
    ("skills/quality-engineer/", ".github/skills/quality-engineer/"),
]

# Claude Code injects the slash-command argument string as $ARGUMENTS. Copilot
# CLI passes the user's request as the agent prompt directly, so there is no
# token to substitute - reword the reference instead.
ARGUMENTS_TOKEN = "$ARGUMENTS"
ARGUMENTS_REPLACEMENT = "the request you were invoked with"


class GeneratedFile:
    """A single output file plus the bytes it should contain."""

    def __init__(self, path: Path, content: bytes):
        self.path = path
        self.content = content


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Parse a leading `---` YAML-ish frontmatter block.

    Only flat `key: value` pairs are used in these files, so a full YAML parser
    is unnecessary. Returns (frontmatter_dict, body). Order of keys is preserved
    via insertion order of the returned dict.
    """
    if not text.startswith("---"):
        return {}, text
    lines = text.splitlines(keepends=True)
    # lines[0] is the opening '---'. Find the closing '---'.
    end = None
    for i in range(1, len(lines)):
        if lines[i].rstrip("\n") == "---":
            end = i
            break
    if end is None:
        return {}, text
    fm: dict[str, str] = {}
    for raw in lines[1:end]:
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        key, sep, value = stripped.partition(":")
        if sep:
            fm[key.strip()] = value.strip()
    body = "".join(lines[end + 1 :])
    return fm, body


def render_frontmatter(fm: dict[str, str]) -> str:
    lines = ["---"]
    for key, value in fm.items():
        lines.append(f"{key}: {value}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def rewrite_body(body: str) -> str:
    for old, new in PATH_REWRITES:
        body = body.replace(old, new)
    body = body.replace(ARGUMENTS_TOKEN, ARGUMENTS_REPLACEMENT)
    return body


def build_agent(src: Path, kind: str) -> GeneratedFile:
    """Transform an agents/ or commands/ markdown file into a .agent.md file.

    `kind` is "agent" or "command" - only used in the provenance header.
    """
    text = src.read_text(encoding="utf-8")
    fm, body = split_frontmatter(text)

    # Copilot agents require a `name`. Agent sources already have one; command
    # sources carry only a description, so derive the name from the filename.
    name = fm.get("name", src.stem)
    description = fm.get("description", "")

    out_fm: dict[str, str] = {"name": name}
    if description:
        out_fm["description"] = description

    header = (
        f"<!-- GENERATED by scripts/build-copilot.py from {kind}s/{src.name}. "
        f"Do not edit directly; run `make build-copilot` after editing the source. -->\n\n"
    )
    content = render_frontmatter(out_fm) + "\n" + header + rewrite_body(body).lstrip("\n")
    out_path = AGENTS_OUT / f"{name}.agent.md"
    return GeneratedFile(out_path, content.encode("utf-8"))


def build_skill() -> list[GeneratedFile]:
    """Mirror the quality-engineer skill verbatim into .github/skills/.

    Files are copied byte-for-byte: SKILL.md frontmatter (name + description) is
    already Copilot-compatible, references are skill-relative, and the scripts /
    JSON resources must not be mutated.
    """
    out: list[GeneratedFile] = []
    for src in sorted(SKILL_SRC.rglob("*")):
        if src.is_dir():
            continue
        rel = src.relative_to(SKILL_SRC)
        out.append(GeneratedFile(SKILL_OUT / rel, src.read_bytes()))
    return out


def collect() -> list[GeneratedFile]:
    files: list[GeneratedFile] = []
    for src in sorted(AGENTS_SRC.glob("*.md")):
        files.append(build_agent(src, "agent"))
    for src in sorted(COMMANDS_SRC.glob("*.md")):
        files.append(build_agent(src, "command"))
    files.extend(build_skill())
    return files


def expected_paths(files: list[GeneratedFile]) -> set[Path]:
    return {f.path for f in files}


def existing_generated_paths() -> set[Path]:
    paths: set[Path] = set()
    for base in (AGENTS_OUT, SKILL_OUT):
        if base.exists():
            paths.update(p for p in base.rglob("*") if p.is_file())
    return paths


def run_check(files: list[GeneratedFile]) -> int:
    stale: list[str] = []
    for f in files:
        if not f.path.exists():
            stale.append(f"missing: {f.path.relative_to(ROOT)}")
        elif f.path.read_bytes() != f.content:
            stale.append(f"outdated: {f.path.relative_to(ROOT)}")
    # Files on disk that the generator no longer produces.
    orphans = existing_generated_paths() - expected_paths(files)
    for o in sorted(orphans):
        stale.append(f"orphaned: {o.relative_to(ROOT)}")

    if stale:
        print("Copilot CLI layer is stale. Run `make build-copilot`:", file=sys.stderr)
        for line in stale:
            print(f"  - {line}", file=sys.stderr)
        return 1
    print("Copilot CLI layer is up to date.")
    return 0


def run_write(files: list[GeneratedFile]) -> int:
    # Remove orphaned generated files first so renames/deletions propagate.
    orphans = existing_generated_paths() - expected_paths(files)
    for o in sorted(orphans):
        o.unlink()
        print(f"removed {o.relative_to(ROOT)}")
    for f in files:
        f.path.parent.mkdir(parents=True, exist_ok=True)
        if f.path.exists() and f.path.read_bytes() == f.content:
            continue
        f.path.write_bytes(f.content)
        print(f"wrote {f.path.relative_to(ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the .github/ tree is up to date; exit non-zero if not",
    )
    args = parser.parse_args()

    for src in (AGENTS_SRC, COMMANDS_SRC, SKILL_SRC):
        if not src.exists():
            print(f"source directory missing: {src}", file=sys.stderr)
            return 2

    files = collect()
    return run_check(files) if args.check else run_write(files)


if __name__ == "__main__":
    raise SystemExit(main())
